apiServer:
  port: 8080
  publicHost: cognitive-load-butler-v2.api.serverpod.space
  publicPort: 443
  publicScheme: https

insightsServer:
  port: 8081
  publicHost: cognitive-load-butler-v2.insights.serverpod.space
  publicPort: 443
  publicScheme: https

webServer:
  port: 8082
  publicHost: cognitive-load-butler-v2.serverpod.space
  publicPort: 443
  publicScheme: https

database:
  requireSsl: true

redis:
  enabled: false

maxRequestSize: 524288

sessionLogs:
  consoleEnabled: true
  persistentEnabled: true
  consoleLogFormat: json

